# Generated by Django 4.2 on 2024-03-06 09:07

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('foodcartapp', '0039_alter_orderelements_options_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='order',
            options={'verbose_name': 'заказ', 'verbose_name_plural': 'заказы'},
        ),
        migrations.AlterModelOptions(
            name='orderelements',
            options={'ordering': ['order'], 'verbose_name': 'элементы заказа', 'verbose_name_plural': 'элементы заказа'},
        ),
        migrations.RenameField(
            model_name='orderelements',
            old_name='count',
            new_name='quantity',
        ),
        migrations.AlterField(
            model_name='orderelements',
            name='product',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='foodcartapp.product', verbose_name='Товар'),
        ),
    ]
