# Generated by Django 4.2 on 2024-03-11 06:01

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('foodcartapp', '0040_alter_order_options_alter_orderelements_options_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='orderelements',
            name='position_cost',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=8, validators=[django.core.validators.MinValueValidator(0)], verbose_name='стоимость позиции'),
            preserve_default=False,
        ),
    ]
