# Generated by Django 4.2 on 2024-03-11 06:27

from django.db import migrations
from django.db.models import F


def calculate_position_cost(apps, schema_editor):
    OrderElements = apps.get_model('foodcartapp', 'OrderElements')
    orders = OrderElements.objects.prefetch_related('product')
    for order in orders.iterator():
        order.position_cost = order.product.price * order.quantity
        order.save()


class Migration(migrations.Migration):
    dependencies = [
        ('foodcartapp', '0041_orderelements_position_cost'),
    ]

    operations = [
        migrations.RunPython(calculate_position_cost),
    ]
