# Generated by Django 4.2 on 2024-03-12 10:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('foodcartapp', '0042_auto_20240311_1427'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='status',
            field=models.CharField(choices=[('new', 'Новый'), ('confirmed', 'Подтвержден'), ('packed', 'Собран'), ('delivered', 'Доставлен')], db_index=True, default='new', max_length=20, verbose_name='статус заказа'),
        ),
    ]
