# Generated by Django 4.2 on 2024-03-12 11:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('foodcartapp', '0045_order_called_at_order_created_at_order_delivered_at'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='payment',
            field=models.CharField(choices=[('cash', 'Наличный'), ('card', 'Безналичный'), ('unknown', 'Неизвестно')], db_index=True, default='unknown', max_length=20, verbose_name='способ оплаты'),
        ),
    ]
